markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: mmcd
author: "michael mcdermott"
email: mmcdermott2#student.gsu.edu
name: "michael mcdermott"
url: http://www.wroth.com
domain: www.wroth.com

twitter_url: http://www.twitter.com/mjmcd
github_url: http://www.github.com/mmcd
linkedin_url: http://www.linkedin.com/in/mjmcdermott
g_analytics: "UA-97870498-1"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4
    css_class: 'syntax_copy_2'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

all_categories: [
["research", "Research","/posts/research.html"], 
["c", "C99/Cuda/C++","/posts/cuda.html"],
["java", "Java","/posts/java.html"],
["python", "Python","/posts/python.html"],
["cluster", "Cluster","/posts/cluster.html"], 
["papers", "Papers","/posts/papers.html"], 
["other", "Other","/posts/other.html"],
# ["rants", "rants","posts/rants.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/EDT

collections:
  docs:
    output: true

gems:
  - jekyll-paginate
  - jemoji
whitelist:
  - jekyll-paginate
  - jemoji

exclude:
  - LICENSE
  - README.md
